// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyNoir_BTL.Models;

public partial class InvoiceDetail
{
    public Guid InvoiceId { get; set; }

    public Guid ProductColorSizeId { get; set; }

    public int Amount { get; set; }

    public decimal Price { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual ProductColorSize ProductColorSize { get; set; }
}