// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyNoir_BTL.Models;

public partial class Product
{
    public Guid Id { get; set; }

    public string ProdName { get; set; }

    public string ProdDesc { get; set; }

    public decimal Price { get; set; }

    public decimal? Width { get; set; }

    public decimal? Height { get; set; }

    public string Type { get; set; }

    public virtual ICollection<ProductColor> ProductColors { get; set; } = new List<ProductColor>();
}