// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyNoir_BTL.Models;

public partial class ProductColor
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string ColorName { get; set; }

    public string ColorCode { get; set; }

    public int Inventory { get; set; }

    public string Size { get; set; }

    public byte[] ImageUrl { get; set; }

    public virtual Product Product { get; set; }
}