// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyNoir_BTL.Models;

public partial class ProductColorSize
{
    public Guid Id { get; set; }

    public Guid ProductColorId { get; set; }

    public string SizeId { get; set; }

    public int Inventory { get; set; }

    public virtual ProductColor ProductColor { get; set; }

    public virtual Size Size { get; set; }
}