// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyNoir_BTL.Models;

public partial class Size
{
    public string Id { get; set; }

    public string SizeName { get; set; }

    public virtual ICollection<ProductColorSize> ProductColorSizes { get; set; } = new List<ProductColorSize>();
}