// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNoir_BTL.Models;

[Table("Vouchers")]
public partial class Voucher
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int MaxUsage { get; set; }

    public int? UsedCount { get; set; }

    public decimal? MinOrderValue { get; set; }

    public bool? Status { get; set; }
}